cluster:
  host: "172.16.4.1:8006"
  host_new: {autohost1: "172.16.4.1:8006", autohost2: "172.16.4.2:8006", autohost3: "172.16.4.3:8006"}
  user: root@pam
  pass: autohost1

db:
  host: "5.227.126.92"
  port: 5432
  user: proxmox
  pass: "Qwerty!23"
  database: diplom
